"""Write docs/vocab_audit.md from the audit outputs saved under reports/audit/.

Every number in the document is read from a JSON file produced by a script,
never typed by hand:
  reports/audit/karsl_counts.json                       (scripts/audit/karsl_counts.py)
  reports/audit/<owner>__<dataset>_files.json            (scripts/audit/kaggle_list_classes.py)
  reports/audit/zenodo_8035320.json                      (this script, by listing the archive)

Usage:  python scripts/audit/build_vocab_audit.py
"""
import json
import re
import subprocess
from collections import Counter
from pathlib import Path

AUDIT = Path("reports/audit")
SEVEN_ZIP = Path("data/tools/7zip/7z.exe")
ZENODO_RAR = Path("data/raw/zenodo_8035320/Dataset.rar")


def list_zenodo_archive():
    """List the videos inside the Zenodo archive and count them per class folder."""
    out = subprocess.run([str(SEVEN_ZIP), "l", "-slt", "-sccUTF-8", str(ZENODO_RAR)],
                         capture_output=True, encoding="utf-8").stdout
    paths = re.findall(r"^Path = (.+\.mp4)$", out, flags=re.MULTILINE)
    per_class = Counter(Path(p.replace("\\", "/")).parent.name for p in paths)
    result = {
        "record": "10.5281/zenodo.8035320",
        "archive_bytes": ZENODO_RAR.stat().st_size,
        "videos": len(paths),
        "videos_per_class": dict(per_class),
    }
    (AUDIT / "zenodo_8035320.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=1), encoding="utf-8")
    return result


def load(name):
    return json.loads((AUDIT / name).read_text(encoding="utf-8"))


def main():
    zenodo = list_zenodo_archive()
    karsl = load("karsl_counts.json")
    extra_a = load("eslamezzat__arabic-sign-language-arsl-for-words-videos_files.json")
    extra_b = load("mohamedsaeed823__arslvideodataset_files.json")
    vocab = json.loads(Path("config/vocab.json").read_text(encoding="utf-8"))
    by_id = {r["sign_id"]: r for r in karsl["signs"]}
    summary = karsl["summary"]

    lines = []
    add = lines.append

    add("# Vocabulary audit (Phase 0)")
    add("")
    add("This file is generated by `scripts/audit/build_vocab_audit.py`. "
        "All counts come from the JSON files in `reports/audit/`.")
    add("")
    add("## 1. Summary")
    add("")
    add("- **Neither primary dataset could be used.** ArabicSL-Net is private, and the Zenodo "
        "\"Arabic words sign language video dataset\" record contains only a tiny sample.")
    add("- **The fallback, KArSL-502, is the only listed source with usable data.** It is used for everything.")
    add("- **KArSL has no fruit, vegetable or shopping words** (no \"want\", \"kilo\", \"price\", \"how much\").")
    add("- **The scenario was therefore changed from a grocery to a pharmacy**, which is still a "
        "\"customer talks to a seller\" situation and is well covered by KArSL's health chapter.")
    add(f"- **Signer IDs exist**: {len(summary['signer_ids'])} signers "
        f"(IDs {', '.join(str(s) for s in summary['signer_ids'])}). "
        "This allows leave-one-signer-out evaluation in Phase 3.")
    add(f"- **{len(vocab['classes'])} classes were chosen** (section 5) and saved in `config/vocab.json`.")
    add("")
    add("## 2. What happened with each source")
    add("")
    add("| Source | Listed in the brief as | What was actually found | Usable |")
    add("|---|---|---|---|")
    add("| ArabicSL-Net (Zenodo 10.5281/zenodo.7771372, Kaggle `deepologylab/arabicsl-net`) | Primary | "
        "The Zenodo record holds only `readme.txt`, which says the dataset is \"still under preparation\" "
        "and available \"privately\" on Kaggle. The Kaggle API answers 403 Forbidden for that dataset, "
        "and a Kaggle search by name and by owner finds nothing public. | No |")
    add(f"| Arabic words sign language video dataset (Zenodo 10.5281/zenodo.8035320) | Primary | "
        f"`Dataset.rar` is {zenodo['archive_bytes']:,} bytes and contains {zenodo['videos']} videos in "
        f"{len(zenodo['videos_per_class'])} class folder "
        f"({', '.join(zenodo['videos_per_class'])}), not the 3000 videos and 30 signs described. "
        "It is only a sample. | No |")
    add(f"| KArSL-502 (https://hamzah-luqman.github.io/KArSL/) | Fallback | "
        f"{summary['total_signs']} signs, {summary['total_videos']:,} samples, "
        f"{len(summary['signer_ids'])} signers, at least {summary['min_videos_per_sign']} samples per sign. | **Yes** |")
    add("")
    add("### How KArSL was obtained")
    add("")
    add("- The official download links point to a university SharePoint. They returned an error page "
        "to scripted downloads, so a public Kaggle copy was used instead: "
        "`yousefdotpy/karsl-502` (video frames, 256x256 pixels, same folder layout as the official release: "
        "signer / split / sign ID / sample).")
    add("- The label sheet `KARSL-502_Labels.xlsx` (SignID, Arabic, English) came from the Kaggle copy "
        "`d3vl0per/karsl-502-labelss`.")
    add("- Per-sample counts and signer IDs came from `metadata.json` in the Kaggle copy "
        "`tfmohamedyahia/kars502-pose-75`. These counts are re-checked against the downloaded frames in Phase 1.")
    add("- Kaggle shows the license of the frame copy as \"unknown\". The KArSL authors ask for a citation "
        "(see `CREDITS.md`).")
    add("")
    add("### Other public datasets seen on Kaggle (not used)")
    add("")
    add("These are **not** in the brief's list of allowed sources, so they were not used. "
        "They are recorded here in case you want to allow them later.")
    add("")
    add("| Kaggle dataset | Classes | Videos | Notes |")
    add("|---|---|---|---|")
    a_classes = sorted({Path(k).name for k in extra_a["videos_per_folder"]})
    add(f"| `{extra_a['dataset']}` | {len(a_classes)}: {', '.join(a_classes)} | "
        f"{sum(extra_a['videos_per_folder'].values())} | "
        "English folder names only, no signer IDs, no documentation of who signed. |")
    b_classes = sorted({Path(k).name for k in extra_b["videos_per_folder"]})
    add(f"| `{extra_b['dataset']}` | {len(b_classes)}: {', '.join(b_classes)} | "
        f"{sum(extra_b['videos_per_folder'].values())} | "
        "Many files are exact copies of each other (names like \"- Copy\"), so the real number of "
        "distinct videos is much smaller. No signer IDs. |")
    add("")
    add("## 3. Signer IDs")
    add("")
    add("- **KArSL:** yes. Every sample belongs to signer 1, 2 or 3, and the signer is part of the folder "
        "and file name. All "
        f"{summary['total_signs']} signs were recorded by all 3 signers"
        + ("." if not summary["signs_without_all_3_signers"] else
           f" except sign IDs {summary['signs_without_all_3_signers']}.")
        )
    add("- **ArabicSL-Net and the Zenodo dataset:** could not be checked, because the data is not available.")
    add("- **Consequence for Phase 3:** leave-one-signer-out evaluation is possible, but with only 3 signers. "
        "One signer is used for training, one for validation (tuning) and one is held out for the final test.")
    add("")
    add("## 4. Things to know about KArSL before trusting the demo")
    add("")
    add("- It was recorded with a Kinect camera in a studio (seated signer, plain green background), "
        "not with a phone. The app will be used with a phone camera, so real-world accuracy can be lower.")
    add("- Only 3 signers. A model can look good on these 3 people and still struggle with a new person.")
    add("- The signs follow the unified Arabic sign language dictionary. Signs used in Oman may differ.")
    add("")
    add("## 5. Chosen vocabulary")
    add("")
    add("Scenario: **at the pharmacy**. Example: \"السلام عليكم\" + \"دواء\" + \"صداع\" + \"شكراً\".")
    add("")
    add("Why these classes:")
    add("")
    add("- Each label is a single clear word in the official label sheet (Arabic and English agree).")
    add("- Each has about 150 samples from all 3 signers (the brief asks for at least about 40).")
    add("- Together they cover greeting, the place, the product and the symptom.")
    add("")
    add("| id | Arabic | English | Source | KArSL SignID | Chapter | Videos | Signers | Videos per signer (1 / 2 / 3) |")
    add("|---|---|---|---|---|---|---|---|---|")
    for c in vocab["classes"]:
        r = by_id[c["karsl_sign_id"]]
        assert r["arabic"] == c["arabic"], (r["arabic"], c["arabic"])
        per = r["videos_per_signer"]
        add(f"| {c['id']} | {c['arabic']} | {c['english']} | {c['source']} | {c['karsl_sign_id']} | "
            f"{r['chapter']} | {r['videos']} | {r['signers']} | "
            f"{per.get('1', 0)} / {per.get('2', 0)} / {per.get('3', 0)} |")
    add("")
    add("Classes considered and left out:")
    add("")
    add("- **Numbers and letters:** static hand shapes that look very similar to each other (for example 2 and 3). "
        "Too easy to confuse for a first version.")
    add("- **\"مريض / مرض\"** and other labels with two words separated by a slash: the label does not say "
        "which of the two meanings the sign has, so they are excluded (rule: do not guess label meaning).")
    add("- **\"صيدلي\" (pharmacist):** likely very close to \"صيدلية\" (pharmacy).")
    add("")
    add("The list may still shrink in Phase 3 if the confusion matrix shows pairs the model cannot separate.")
    add("")
    add("## 6. Every class in every source")
    add("")
    add("### Zenodo 10.5281/zenodo.8035320 (sample only)")
    add("")
    add("| Arabic label | Videos | Signers |")
    add("|---|---|---|")
    for name, n in zenodo["videos_per_class"].items():
        add(f"| {name} | {n} | unknown |")
    add("")
    add("### ArabicSL-Net")
    add("")
    add("No class list is available (private dataset).")
    add("")
    add("### KArSL-502")
    add("")
    add("| SignID | Arabic | English | Chapter | Videos | Signers |")
    add("|---|---|---|---|---|---|")
    for r in karsl["signs"]:
        add(f"| {r['sign_id']} | {r['arabic']} | {r['english']} | {r['chapter']} | {r['videos']} | {r['signers']} |")
    add("")

    Path("docs").mkdir(exist_ok=True)
    Path("docs/vocab_audit.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote docs/vocab_audit.md ({len(lines)} lines)")


if __name__ == "__main__":
    main()
