"""Write docs/REPORT.md from the files in reports/.

Every number in the report is read from a JSON file that a script produced:
    reports/extraction_report.json   (scripts/build_features.py)
    reports/training_report.json     (scripts/train.py)
    reports/metrics.json             (scripts/evaluate.py)
    reports/parity_report.json       (web/e2e/parity.spec.js)
    reports/e2e_report.json          (web/e2e/camera.spec.js)
    reports/lighthouse.report.json   (Lighthouse)

Usage:  python scripts/write_report.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from jisr.vocab import load_vocab  # noqa: E402


def load(name):
    path = Path("reports") / name
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def pct(x):
    return "n/a" if x is None else f"{100 * x:.1f}%"


def main():
    vocab = load_vocab()
    extraction = load("extraction_report.json")
    training = load("training_report.json")
    metrics = load("metrics.json")
    parity = load("parity_report.json")
    e2e = load("e2e_report.json")
    lighthouse = load("lighthouse.report.json")

    lines = []
    add = lines.append
    add("# Results report")
    add("")
    add("Generated by `scripts/write_report.py` from the files in `reports/`. "
        "No number in this file was typed by hand.")
    add("")

    # ---- Vocabulary ----
    add("## 1. Vocabulary")
    add("")
    add(f"Scenario: **{vocab['scenario']}**. All words come from the KArSL-502 dataset "
        "(see `docs/vocab_audit.md` for why the two primary datasets could not be used).")
    add("")
    add("| id | Arabic | English | KArSL sign | Clips used (signers 1 / 2 / 3) |")
    add("|---|---|---|---|---|")
    for c in vocab["classes"]:
        stats = extraction["classes"][str(c["id"])] if extraction else None
        per = stats["kept_per_signer"] if stats else {}
        ids = " + ".join(str(i) for i in c.get("karsl_sign_ids", [c["karsl_sign_id"]]))
        add(f"| {c['id']} | {c['arabic']} | {c['english']} | {ids} | "
            f"{per.get('1', 0)} / {per.get('2', 0)} / {per.get('3', 0)} |")
    other = vocab["other_class"]
    add("")
    add(f"Plus one extra class, **\"{other['label']}\" (other sign)**, made from "
        f"{len(other['train_sign_ids'])} KArSL signs outside the vocabulary for training, "
        f"{len(other['validation_sign_ids'])} different signs for validation and "
        f"{len(other['test_sign_ids'])} different signs for the test "
        f"({other['clips_per_sign_per_signer']} clips per sign and signer). "
        "It lets the app answer \"unclear\" for gestures it does not know.")
    add("")

    # ---- Data ----
    if extraction:
        add("## 2. Data after landmark extraction")
        add("")
        add("Words: a *landmark* is a point MediaPipe finds on the body (fingertip, wrist, shoulder). "
            "A clip is *dropped* when MediaPipe never found a hand or a body in it.")
        add("")
        add(f"- Clips processed: **{extraction['total_clips']}**, kept: **{extraction['total_kept']}**, "
            f"dropped: **{extraction['total_dropped']}**.")
        add(f"- Frames in which at least one hand was found: **{extraction['frames_with_a_hand_percent']}%**.")
        add(f"- Frames removed by the trim step (hand raise and lowering, step 3 of `docs/features.md`): "
            f"**{extraction['frames_trimmed_percent']}%**. The training clips start with the hand already up, "
            "so the step removes almost nothing from them; in the app it removes the travel of the hand.")
        add("")
        add("| Class | Clips | Kept | Dropped (no hand) | Hand found in frames |")
        add("|---|---|---|---|---|")
        for class_id, stats in extraction["classes"].items():
            add(f"| {stats['label']} | {stats['clips']} | {stats['kept']} | {stats['dropped_no_hands']} | "
                f"{stats['frames_with_a_hand_percent']}% |")
        add("")

    # ---- Protocol ----
    add("## 3. Evaluation protocol (how the numbers were measured)")
    add("")
    add("KArSL has **3 signers**, and every clip says who signed it. We used this to measure accuracy on a person "
        "the model has never seen, which is the only honest way to estimate how the app behaves for a new user.")
    add("")
    if training:
        cfg = training["config"]
        add(f"1. **Validation rounds** on the development signers {cfg['dev_signers']}: train on one, check on the "
            "other, and the other way round. All choices (model type, settings, number of epochs, the temperature "
            "and the rejection threshold) were made from these rounds only.")
        add(f"2. **Final model** trained on signers {cfg['dev_signers']} together, for {cfg['max_epochs']} epochs, "
            f"with data augmentation (mirroring, rotation, scaling, speed change, dropped frames, noise).")
        add(f"3. **One test** on signer {cfg['test_signer']}, who was never used for any decision. "
            "The numbers below are from that single run.")
    add("")
    add("Words: *overfitting* is when a model learns the training clips by heart and does badly on new ones; "
        "testing on a new signer shows whether that happened. *Top-1* is the share of clips whose best guess is "
        "right; *top-3* is the share whose correct word is among the three candidates the app shows.")
    add("")

    # ---- Validation ----
    if training:
        add("## 4. Validation rounds (development signers)")
        add("")
        add("| Train on | Check on | Clips checked | CNN top-1 | CNN top-3 | Baseline kNN-DTW top-1 |")
        add("|---|---|---|---|---|---|")
        for fold in training["folds"]:
            knn = fold.get("knn_dtw", {}).get("top1")
            add(f"| signer {fold['train_signers'][0]} | signer {fold['validation_signer']} | "
                f"{fold['validation_clips']} | {pct(fold['cnn']['top1'])} | {pct(fold['cnn']['top3'])} | {pct(knn)} |")
        vm = training["validation_mean"]
        add(f"| **mean** | | | **{pct(vm['cnn_top1'])}** | **{pct(vm['cnn_top3'])}** | "
            f"**{pct(vm.get('knn_dtw_top1'))}** |")
        add("")
        add(f"Chosen model: **{training['chosen_model']}** "
            f"({training['final_model']['parameters']:,} parameters, "
            f"{training['final_model']['onnx_bytes'] / 1e6:.2f} MB as ONNX). "
            "The baseline (nearest neighbour with dynamic time warping) only knows the vocabulary words.")
        add("")
        if "shipped_model" in training:
            sm = training["shipped_model"]
            add("### Measured model and shipped model")
            add("")
            add(f"The numbers in section 5 are for the model trained on signers {training['final_model']['train_signers']} "
                f"(`models/jisr_model_measured.onnx`). The app ships a second model trained with exactly the same "
                f"recipe on signers {sm['train_signers']} ({sm['train_clips']} clips, `models/jisr_model.onnx`), because "
                "more signers usually mean better recognition of a new person. **Its accuracy on new signers cannot be "
                "measured** (there is no fourth signer), so no number is claimed for it; it should be at least as good "
                "as the measured model, but that is an expectation, not a measurement. The browser tests in section 6 "
                "compare the browser with Python on the shipped model.")
            add("")

    # ---- Test ----
    if metrics:
        t = metrics["test"]
        add("## 5. Held-out signer test (the accuracy gate)")
        add("")
        add(f"Signer {metrics['protocol']['test_signer']}, {t['vocabulary_clips']} vocabulary clips, "
            f"{metrics['test_with_rejection']['unknown_sign_clips']} unknown-sign clips.")
        add("")
        add("| Measure | Result | Target | Met? |")
        add("|---|---|---|---|")
        add(f"| Top-1 accuracy | **{pct(t['top1_accuracy'])}** | {pct(t['target_top1'])} | "
            f"{'yes' if t['top1_accuracy'] >= t['target_top1'] else 'no'} |")
        add(f"| Top-3 accuracy | **{pct(t['top3_accuracy'])}** | {pct(t['target_top3'])} | "
            f"{'yes' if t['top3_accuracy'] >= t['target_top3'] else 'no'} |")
        add("")
        cal = metrics["calibration"]
        app = metrics["test_with_rejection"]
        add("### With the rejection threshold (what the app does)")
        add("")
        add("Words: *calibration* (temperature scaling) corrects the model's confidence so that \"80%\" really "
            "means right about 8 times in 10. The *rejection threshold* is the confidence below which the app says "
            "\"unclear, repeat the sign\" instead of showing candidates.")
        add("")
        add(f"- Temperature: **{cal['temperature']}**, threshold: **{cal['threshold']:.2f}** "
            f"(both chosen on {cal['chosen_on']}).")
        add(f"- Vocabulary clips accepted (candidates shown): **{pct(app['acceptance_rate'])}**.")
        add(f"- Top-1 accuracy on the accepted clips: **{pct(app['accuracy_on_accepted'])}**.")
        add(f"- Unknown signs correctly rejected: **{pct(app['unknown_sign_rejection_rate'])}**.")
        conf = metrics["confidence"]
        add(f"- Mean confidence when the best guess is right: **{pct(conf['mean_when_correct'])}**; "
            f"when it is wrong: **{pct(conf['mean_when_wrong'])}**.")
        add("")
        add("![confidence](figures/confidence.png)")
        add("")
        add("### Per class")
        add("")
        add("Words: *recall* is the share of real clips of a word that the model found; *precision* is the share "
            "of the model's answers for a word that were right.")
        add("")
        add("The last two columns are what the user experiences: how often the app showed candidates "
            "(instead of \"unclear\"), and how often the correct word was among the 3 candidates **and** the app "
            "showed them.")
        add("")
        add("| Class | Clips | Precision | Recall | Accepted by the app | Accepted and in top 3 |")
        add("|---|---|---|---|---|---|")
        for row in metrics["per_class"]:
            add(f"| {row['label']} | {row['clips']} | {pct(row['precision'])} | {pct(row['recall'])} | "
                f"{pct(row.get('accepted'))} | {pct(row.get('accepted_and_in_top3'))} |")
        weak = [r for r in metrics["per_class"] if r.get("accepted") is not None and r["accepted"] < 0.5]
        if weak:
            add("")
            add("**Words that do not work for the held-out signer:** " +
                ", ".join(f"{r['label']} (accepted {pct(r['accepted'])})" for r in weak) +
                ". The model answers \"other sign\" for most of this signer's clips of these words, so the app "
                "says \"unclear\" instead of offering them. The top-1 and top-3 numbers above only rank the words, "
                "so they do not show this; the acceptance rate does.")
        add("")
        add("### Confusion matrix")
        add("")
        add("Words: a *confusion matrix* is a table with the true sign in the rows and the model's answer in the "
            "columns; numbers off the diagonal are mistakes, and they show which signs get mixed up.")
        add("")
        add("![confusion matrix](figures/confusion_matrix.png)")
        add("")
        add("Full numbers: `reports/metrics.json`.")
        add("")

    # ---- Browser tests ----
    add("## 6. Browser tests")
    add("")
    if parity:
        add(f"**Feature parity** (`reports/parity_report.json`): {parity['clips']} held-out clips went through the "
            "Python feature code and the browser feature code, frame by frame, with the same pictures. "
            f"Mean difference between the two feature tables: **{parity['mean_difference_over_all_clips']:.5f}** "
            f"(features are measured in shoulder widths; limit {parity['limit_mean_difference']}), "
            f"median per clip {parity.get('median_clip_mean_difference', float('nan')):.5f}; clips within the limit: "
            f"**{pct(parity['clips_within_limit'])}**; same model answer: **{pct(parity['same_answer'])}**. "
            f"In {parity.get('clips_with_a_hand_detection_flip', '?')} clips the two MediaPipe builds disagreed about "
            "whether a hand was visible in at least one frame; this is where the larger differences come from.")
        add("")
    if e2e:
        add(f"**End to end with a fake camera** (`reports/e2e_report.json`): {e2e['clips']} held-out clips were played "
            "to the real app as a camera stream, with a grey pause between clips. The app found the start and end of "
            "each sign, built the features and ran the model on its own.")
        add("")
        rows = e2e["rows"]
        same_response = sum(
            1 for r in rows if r["browser_kind"] == r["python_kind"]
            and (r["python_kind"] == "unclear" or r["same_word"])) / len(rows)
        detected = [r for r in rows if r["browser_kind"] != "not detected"]
        add(f"- Browser top word agrees with Python: **{pct(e2e['agreement_top_word'])}** "
            f"(target 95%: **{'met' if e2e['agreement_top_word'] >= 0.95 else 'not met'}**).")
        add(f"- Same answer shown to the user (same word, or both say \"unclear\"): **{pct(same_response)}**.")
        add(f"- Same accept/unclear decision: **{pct(e2e['agreement_ok_or_unclear'])}**.")
        add(f"- Among the {len(detected)} clips the app did detect: same top word "
            f"**{pct(sum(r['same_word'] for r in detected) / len(detected))}**, same decision "
            f"**{pct(sum(r['browser_kind'] == r['python_kind'] for r in detected) / len(detected))}**.")
        add(f"- Clips the app did not detect at all: **{e2e['clips_not_detected']}**; extra detections: "
            f"**{e2e['extra_detections']}**.")
        add(f"- Browser top word is the true word: **{pct(e2e['browser_top_word_is_true_label'])}** "
            f"(Python on the same video: {pct(e2e['python_top_word_is_true_label'])}).")
        if "browser_frames_per_second" in e2e:
            add(f"- The browser processed **{e2e['browser_frames_per_second']:.1f} frames per second** on the test "
                f"laptop (MediaPipe on the {e2e.get('mediapipe_delegate')}), while the video plays at 25; "
                "so the app saw about every second frame, unlike Python, which saw them all.")
        add("")
    if lighthouse:
        scores = {k: v["score"] for k, v in lighthouse["categories"].items()}
        add("**Lighthouse** (`reports/lighthouse.report.json`): " +
            ", ".join(f"{k} {int(round(v * 100))}" for k, v in scores.items()) +
            ". (Lighthouse removed its separate PWA category in 2024; offline use is checked by "
            "`web/e2e/offline.spec.js` instead.)")
        add("")

    Path("docs/REPORT.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote docs/REPORT.md ({len(lines)} lines)")


if __name__ == "__main__":
    main()
